calibration_tom/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('network/', include('network.urls', namespace='network')),
    path('', include('tom_common.urls')),
    path('photometric_standards/', include('photometric_standards.urls', namespace='photometric_standards')),
    path('nres/', include('nres_calibrations.urls', namespace='nres_calibrations')),
    path('calibrations/', include('calibrations.urls')),
    # admin comes from somewhere else
]

# this is to serve static file from a debug Dockerfile environment (performs a findstatic)
# (i.e. without this a local Dockerfile-deployed instance won't find the staticfiles from
# the other INSTALLED_APPS)
urlpatterns += staticfiles_urlpatterns()

calibrations/urls.py
from django.urls import path
from django.views.generic import TemplateView
from calibrations.views import CalibrationSubmissionView

app_name = 'calibrations'

urlpatterns = [
    path('', CalibrationSubmissionView.as_view(), name='calibrations_index'),
    path('bias/', TemplateView.as_view(template_name="calibrations/bias_stub.html"), name='bias_home'),
    path('dark/', TemplateView.as_view(template_name="calibrations/dark_stub.html"), name='dark_home'),
    path('flat/', TemplateView.as_view(template_name="calibrations/flat_stub.html"), name='flat_home'),
]

network/urls.py
from django.urls import path

from .views import InstrumentListView, InstrumentGroupView, InstrumentDetailView

from .api_views import InstrumentViewSet
from tom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()
router.register(r'instruments', InstrumentViewSet, 'instruments')

app_name = 'network'

urlpatterns = [
    path('instruments/', InstrumentListView.as_view(), name='instrument_list'),
    path('instrumentgroup/', InstrumentGroupView.as_view(), name='instrumentgroup'),
    path('<int:pk>/', InstrumentDetailView.as_view(), name='detail'),
]

nres_calibrations/urls.py
from django.urls import path

from nres_calibrations.views import NRESCalibrationsView, NRESCalibrationSubmissionView
from nres_calibrations.views import InstrumentListView
from nres_calibrations.views import InstrumentTargetDetailView
from nres_calibrations.views import InstrumentTargetListView
from nres_calibrations.views import InstrumentTypeListView
from nres_calibrations.views import NRESCadenceToggleView, NRESCadenceDeleteView

# app_name is required in order to specify a namespace in include()
app_name = 'nres_calibrations'

urlpatterns = [
    path('nres', NRESCalibrationsView.as_view(), name='nres_home'),
    # TODO: rename this path
    path('submit-cadence', NRESCalibrationSubmissionView.as_view(), name='nres_submission'),
    path('instruments', InstrumentTypeListView.as_view(), name='instrument_type_list'),
    path('instruments/<str:instrument_type>/', InstrumentListView.as_view(), name='instrument_list'),
    path('instruments/<str:instrument_type>/<str:instrument_code>/', InstrumentTargetListView.as_view(),
         name='instrument_target_list'),
    path('instruments/<str:instrument_type>/<str:instrument_code>/<int:pk>/', InstrumentTargetDetailView.as_view(),
         name='instrument_target_detail'),
    path('cadence-toggle/<int:pk>/', NRESCadenceToggleView.as_view(), name='cadence_toggle'),
    path('cadence-delete/<int:pk>/', NRESCadenceDeleteView.as_view(), name='cadence_delete')
]

photometric_standards/urls.py
from django.urls import path

from photometric_standards.views import PhotometricStandardsView, PhotometricStandardsForm, PhotometricStandardsTargets
from photometric_standards.views import PhotometricStandardsCadencesView, PhotometricStandardsCadencesSiteView, PhotometricStandardsCadencesList, PhotometricStandardsCadenceToggleView, PhotometricStandardsCadenceDeleteView

app_name = 'photometric_standards'

urlpatterns = [
    path('cadences/', PhotometricStandardsCadencesView.as_view(), name='photometric_standards_cadences'),
    path('cadence-toggle/<int:pk>/', PhotometricStandardsCadenceToggleView.as_view(), name='cadence_toggle'),
    path('cadence-delete/<int:pk>/', PhotometricStandardsCadenceDeleteView.as_view(), name='cadence_delete'),
    path('form/', PhotometricStandardsForm.as_view(), name='photometric_standards_form'),
    path('targets/', PhotometricStandardsTargets.as_view(), name='photometric_standards_targets'),
    path('site/<str:site>/', PhotometricStandardsCadencesSiteView.as_view(), name='site_detail')
]

templates/tom_common/base.html
{% load static bootstrap4 %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'tom_common/css/main.css' %}">
    {% block additional_css %}
    {% endblock %}
    <link rel="icon" type="image/x-icon" href="{% static 'tom_common/img/favicon-32.ico' %}" sizes="32x32" />
    <link rel="icon" type="image/x-icon" href="{% static 'tom_common/img/favicon-16.ico' %}" sizes="16x16" />

    {% bootstrap_javascript jquery='True' %}

    <title>LCO Calibration TOM | {% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="/"><img src="{% static 'tom_common/img/logo-color-cropped.png' %}" class="img-fluid"> LCO Calibration TOM</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% comment "Navbar Content Template" %}
          The navbar_content.html template defines the list (li) of nav-items that appear
          in the navbar-nav (ul).

          To customize your navbar-nav in your TOM:
          1. Create a templates/tom_common directory at the project level.
          2. Copy tom_common/templates/tom_common/navbar_content.html to your project's
             templates/tom_common directory.
          3. Customize your navbar content by editing your navbar_content.html.

          For more information,
          see the Django tutorial, "Writing your first Django app",
          Part 7, Section "Customize the admin look and feel"
          {% endcomment %}
          {% include 'tom_common/navbar_content.html' %}

        </ul>
        <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            {% if user.first_name or user.last_name %}
            <a class="nav-link" href="{% url 'user-update' user.id %}">{{ user.first_name }} {{ user.last_name }} ({{ user.username }})</a>
            {% else %}
            <a class="nav-link" href="{% url 'user-update' user.id %}">{{ user.username }}</a>
            {% endif %}
          </li>
          <li>
            <a class="btn btn-outline-success" title="logout" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="btn btn-outline-success" title="logout" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
        </ul>
      </div>
    </nav>

    <main role="main" class="container">
      {% bootstrap_messages %}
      <div class="content">
        {% block content %}
        {% endblock %}
      </div>

    </main>

  {% block javascript %}
    {% endblock %}
    {% block extra_javascript %}
    {% endblock %}
  </body>
</html>

templates/tom_common/index.html
{% extends 'tom_common/base.html' %}
{% load static targets_extras observation_extras dataproduct_extras tom_common_extras %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-8">
    <h2 class="text-center">LCO Calibration TOM</h2>
    <p class="text-center"><img src="{% static 'img/calibration.jpg' %}" class="img-fluid mx-auto"></p>
    <h3>Next steps</h3>
    <ul>
      <li>
        Check out the <a href="https://tom-toolkit.readthedocs.io/en/stable/" title="TOM Toolkit home page">TOM
        Toolkit homepage</a> for the latest news, downloads and documentation.
      </li>
      <li>
        <a href="{% url 'targets:create' %}" title="Create Target">Add your first target</a>.
      </li>
      <li>
        Customize this page by editing the
        <code>templates/tom_common/index.html</code> file or by editing your
        project's <code>urls.py</code>.
      </li>
      <li>
        Take a look at some <a href="https://tom-toolkit.readthedocs.io/en/stable/customization/common_customizations.html">common first customizations</a>.
      </li>
    </ul>
    <h3>Other Resources</h3>
    <ul>
      <li>The official <a href="https://www.djangoproject.com/">Django documentation</a>.</li>
      <li>The official <a href="http://www.astropy.org/">Astropy documentation</a>.</li>
    </ul>
  </div>
  <div class="col-md-4">
    <div class="card">
      <div class="card-header">
        Latest Comments
      </div>
      {% recent_comments %}
    </div>
    <br/>
    <div class="card">
      <div class="card-header">
        Latest Targets
      </div>
      {% recent_targets %}
  </div>
</div>
{% endblock %}

templates/tom_common/navbar_content.html
{% load bootstrap4 %}
{% comment %}
The following nav-item list elements (li) are included in the tom_common/base.html navbar-nav (ul).
{% endcomment %}
<li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown">Network</a>
    <ul class="dropdown-menu">
        <li class="nav-item {% if request.resolver_match.namespace == 'network' %}active{% endif %}">
            <a class="nav-link" href="{% url 'network:instrument_list' %}"><font color="black">Instruments</font></a>
        </li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown">Targets</a>
    <ul class="dropdown-menu">
        <li class="nav-item {% if request.resolver_match.namespace == 'targets' %}active{% endif %}">
            <a class="nav-link" href="{% url 'targets:list' %}"><font color="black">Targets</font></a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'targets' %}active{% endif %}">
            <a class="nav-link" href="{% url 'targets:targetgrouping' %}"><font color="black">Target Grouping</font></a>
        </li>
    </ul>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown">Observations</a>
    <ul class="dropdown-menu">
        <li class="nav-item {% if request.resolver_match.namespace == 'observations' %}active{% endif %}">
            <a class="nav-link" href="{% url 'tom_observations:list' %}" style="color:black">Observations</a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'observations' %}active{% endif %}">
            <a class="nav-link" href="{% url 'tom_observations:group-list' %}" style="color:black">Observation Groups</a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'observations' %}active{% endif %}">
            <a class="nav-link" href="{% url 'tom_observations:template-list' %}" style="color:black">Observation Templates</a>
        </li>
    </ul>
</li>
<li class="nav-item {% if request.resolver_match.namespace == 'dataproducts' %}active{% endif %}">
    <a class="nav-link" href="{% url 'tom_dataproducts:list' %}">Data</a>
</li>
<li class="nav-item {% if 'user' in request.resolver_match.url_name %}active{% endif %}">
    <a class="nav-link" href="{% url 'user-list' %}">Users</a>
</li>

<li class="nav-item {% if 'user' in request.resolver_match.url_name %}active{% endif %}">
    <a class="nav-link" href="{% url 'nres_calibrations:nres_home' %}"><p style="text-align:center; margin:0; padding:0">NRES</p><p style="text-align:center; margin:0; padding:0">Standards</p></a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown"><p style="text-align:center; margin:0; padding:0">Photometric</p><p style="text-align:center; margin:0; padding:0">Standards</p></a>
    <ul class="dropdown-menu">
        <li class="nav-item {% if request.resolver_match.namespace == 'photometric_standards' %}active{% endif %}">
            <a class="nav-link" href="{% url 'photometric_standards:photometric_standards_cadences' %}" style="color:black">Cadences</a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'photometric_standards' %}active{% endif %}">
            <a class="nav-link" href="{% url 'photometric_standards:photometric_standards_form' %}" style="color:black">Request Form</a>
        </li>
        <li class="nav-item {% if request.resolver_match.namespace == 'photometric_standards' %}active{% endif %}">
            <a class="nav-link" href="{% url 'photometric_standards:photometric_standards_targets' %}" style="color:black">Fields</a>
        </li>
    </ul>
</li>
<li class="nav-item {% if 'user' in request.resolver_match.url_name %}active{% endif %}">
    <a class="nav-link" href="{% url 'calibrations:bias_home' %}">Bias</a>
</li>
<li class="nav-item {% if 'user' in request.resolver_match.url_name %}active{% endif %}">
    <a class="nav-link" href="{% url 'calibrations:dark_home' %}">Dark</a>
</li>
<li class="nav-item {% if 'user' in request.resolver_match.url_name %}active{% endif %}">
    <a class="nav-link" href="{% url 'calibrations:flat_home' %}">Flat</a>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown">Documentation</a>
    <ul class="dropdown-menu">
        <li class="nav-item active">
            <a class="nav-link" href="https://docs.google.com/document/d/1dpfSSYDeRUz4Rlnxck8wuRIp54A47JS3IO8-DX-sGGk/" target="_blank" style="color:black">User Guide</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="https://github.com/LCOGT/calibration-tom" target="_blank" style="color:black">Source Code</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="https://tom-toolkit.readthedocs.io/en/stable/" target="_blank" style="color:black">TOM Toolkit</a>
        </li>
    </ul>
</li>