bias_calibrations/urls.py
from django.urls import path

from bias_calibrations.views import BiasCalibrationsView, BiasCalibrationsForm, BiasCalibrationsTargets
from bias_calibrations.views import BiasCalibrationsCadencesView, BiasCalibrationsCadencesSiteView, BiasCalibrationsCadencesList, BiasCalibrationsCadenceToggleView, BiasCalibrationsCadenceDeleteView

app_name = 'bias_calibrations'

urlpatterns = [
    path('cadences/', BiasCalibrationsCadencesView.as_view(), name='bias_calibrations_cadences'),
    path('cadence-toggle/<int:pk>/', BiasCalibrationsCadenceToggleView.as_view(), name='cadence_toggle'),
    path('cadence-delete/<int:pk>/', BiasCalibrationsCadenceDeleteView.as_view(), name='cadence_delete'),
    path('form/', BiasCalibrationsForm.as_view(), name='bias_calibrations_form'),
    path('targets/', BiasCalibrationsTargets.as_view(), name='bias_calibrations_targets'),
    path('site/<str:site>/', BiasCalibrationsCadencesSiteView.as_view(), name='site_detail')
]

calibration_tom/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('network/', include('network.urls', namespace='network')),
    path('', include('tom_common.urls')),
    path('photometric_standards/', include('photometric_standards.urls', namespace='photometric_standards')),
    path('nres/', include('nres_calibrations.urls', namespace='nres_calibrations')),
    path('calibrations/', include('calibrations.urls')),
    # admin comes from somewhere else
]

# this is to serve static file from a debug Dockerfile environment (performs a findstatic)
# (i.e. without this a local Dockerfile-deployed instance won't find the staticfiles from
# the other INSTALLED_APPS)
urlpatterns += staticfiles_urlpatterns()

network/urls.py
from django.urls import path

from .views import InstrumentListView, InstrumentGroupView, InstrumentDetailView

from .api_views import InstrumentViewSet
from tom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()
router.register(r'instruments', InstrumentViewSet, 'instruments')

app_name = 'network'

urlpatterns = [
    path('instruments/', InstrumentListView.as_view(), name='instrument_list'),
    path('instrumentgroup/', InstrumentGroupView.as_view(), name='instrumentgroup'),
    path('<int:pk>/', InstrumentDetailView.as_view(), name='detail'),
]

bias_calibrations/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import ButtonHolder, Column, Layout, Row, Submit
from django import forms
from django.conf import settings
from django.urls import reverse
from django.contrib.auth.models import Group

from tom_targets.models import Target
from tom_targets.forms import CoordinateField

from .models import BiasTarget, BiasTargetExtra, HOUR_ANGLE_FIELDS, REQUIRED_HOUR_ANGLE_FIELDS



class BiasCalibrationsCadenceSubmissionForm(forms.Form):
    site = forms.ChoiceField(required=True,
                             choices=[('all', 'All Sites')] + [(site, site) for site in settings.BIAS_SITES],
                             label=False)
    cadence_frequency = forms.IntegerField(label=False, min_value=1,
                                   widget=forms.NumberInput(attrs={'placeholder': 'Frequency (hours)'}))
    target_id = forms.ChoiceField(choices=[])  # Display standard type alongside target name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # target_id choices must  be defined here in the __init__ rather than in the class definition
        # because the target_is_in_season method used below is added dynamically to the Target class
        # and it doesn't yet exist at the time of class interpretation, but it does when the instance
        # is made (and __init__ is called)
        self.fields['target_id'] = forms.ChoiceField(  # Create choices for standard_types of targets currently in season
            choices=[(target.id,
                      f"{target.targetextra_set.filter(key='standard_type').first().value} (currently {target.name})")
                     for target in BiasTarget.objects.filter(targetextra__key='calibration_type', targetextra__value='BIAS')
                     if target.target_is_in_season()],
            label=False
        )
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('bias_calibrations:bias_calibrations_submission')

        self.helper.layout = Layout(
            Row(
                Column('site'),
                Column('cadence_frequency'),
                Column('target_id'),
                Column(
                    ButtonHolder(
                        Submit('submit', 'Update or Create Cadence')
                    )
                )
            )
        )

class BiasTargetForm(forms.ModelForm):
    groups = forms.ModelMultipleChoiceField(Group.objects.none(), required=False, widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.extra_fields = {}
        for extra_field in settings.BIAS_EXTRA_FIELDS:
            # Add extra fields to the form
            field_name = extra_field['name']
            self.extra_fields[field_name] = extra_field_to_form_field(extra_field['type'])
            # Populate them with initial values if this is an update
            if kwargs['instance']:
                te = BiasTargetExtra.objects.filter(target=kwargs['instance'], key=field_name)
                if te.exists():
                    self.extra_fields[field_name].initial = te.first().typed_value(extra_field['type'])

            self.fields.update(self.extra_fields)

    def save(self, commit=True):
        instance = super().save(commit=commit)
        if commit:
            for field in settings.BIAS_EXTRA_FIELDS:
                if self.cleaned_data.get(field['name']) is not None:
                    BiasTargetExtra.objects.update_or_create(
                            target=instance,
                            key=field['name'],
                            defaults={'value': self.cleaned_data[field['name']]}
                    )
            # Save groups for this target
            for group in self.cleaned_data['groups']:
                assign_perm('tom_targets.view_target', group, instance)
                assign_perm('tom_targets.change_target', group, instance)
                assign_perm('tom_targets.delete_target', group, instance)
            for group in get_groups_with_perms(instance):
                if group not in self.cleaned_data['groups']:
                    remove_perm('tom_targets.view_target', group, instance)
                    remove_perm('tom_targets.change_target', group, instance)
                    remove_perm('tom_targets.delete_target', group, instance)

        return instance

    class Meta:
        abstract = True
        model = BiasTarget
        fields = '__all__'
        widgets = {'type': forms.HiddenInput()}


class HourAngleTargetCreateForm(BiasTargetForm):
    ha = CoordinateField(required=True, label='Hour Angle', c_type='ha',
                         help_text='Hour Angle, in decimal or sexagesimal hours. See '
                                   'https://docs.astropy.org/en/stable/api/astropy.coordinates.Angle.html for '
                                   'supported sexagesimal inputs.')
    dec = CoordinateField(required=True, label='Declination', c_type='dec',
                          help_text='Declination, in decimal or sexagesimal degrees. See '
                                    ' https://docs.astropy.org/en/stable/api/astropy.coordinates.Angle.html for '
                                    'supported sexagesimal inputs.')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in REQUIRED_HOUR_ANGLE_FIELDS:
            self.fields[field].required = True

    class Meta(BiasTargetForm.Meta):
        fields = HOUR_ANGLE_FIELDS

bias_calibrations/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView, DeleteView
from django.views.generic.edit import FormView, CreateView
from tom_observations.models import DynamicCadence

from calibrations.facilities.bias_calibrations_facility import BiasCalibrationsManualSubmissionForm
from calibrations.models import Filter, Instrument, InstrumentFilter

from .models import BiasTarget
from .forms import HourAngleTargetCreateForm


logger = logging.getLogger(__name__)

class BiasTargetCreateView(LoginRequiredMixin, CreateView):
    """
    View for creating a Target. Requires authentication.
    """

    model = BiasTarget
    fields = '__all__'

    def get_default_target_type(self):
        """
        Returns the user-configured target type specified in ``settings.py``, if it exists, otherwise returns hour_angle

        :returns: User-configured target type or global default
        :rtype: str
        """
        try:
            return settings.BIAS_TARGET_TYPE
        except AttributeError:
            return BiasTarget.HOUR_ANGLE

    def get_target_type(self):
        """
        Gets the type of the target to be created from the query parameters. If none exists, use the default target
        type specified in ``settings.py``.

        :returns: target type
        :rtype: str
        """
        obj = self.request.GET or self.request.POST
        target_type = obj.get('type')
        # If None or some invalid value, use default target type
        if target_type not in (BiasTarget.HOUR_ANGLE):
            target_type = self.get_default_target_type()
        return target_type

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.

        :returns: Dictionary with the following keys:

                  `type`: ``str``: Type of the target to be created

                  `groups`: ``QuerySet<Group>`` Groups available to the current user

        :rtype: dict
        """
        return {
            'type': self.get_target_type(),
            'groups': self.request.user.groups.all(),
            **dict(self.request.GET.items())
        }

    def get_form_class(self):
        """
        Return the form class to use in this view.

        :returns: form class for target creation
        :rtype: subclass of TargetCreateForm
        """
        target_type = self.get_target_type()
        self.initial['type'] = target_type
        if target_type == BiasTarget.HOUR_ANGLE:

            return HourAngleTargetCreateForm


    def form_valid(self, form):
        """
        Runs after form validation. Creates the ``BiasTarget``, and creates any ``TargetName`` or ``TargetExtra`` objects,
        then runs the ``target_post_save`` hook and redirects to the success URL.

        :param form: Form data for target creation
        :type form: subclass of TargetCreateForm
        """
        super().form_valid(form)
        extra = TargetExtraFormset(self.request.POST)
        names = TargetNamesFormset(self.request.POST)
        if extra.is_valid() and names.is_valid():
            extra.instance = self.object
            extra.save()
            names.instance = self.object
            names.save()
        else:
            form.add_error(None, extra.errors)
            form.add_error(None, extra.non_form_errors())
            form.add_error(None, names.errors)
            form.add_error(None, names.non_form_errors())
            return super().form_invalid(form)

        logger.info('Target post save hook: %s created: %s', self.object, True)
        run_hook('target_post_save', target=self.object, created=True)
        return redirect(self.get_success_url())

    def get_form(self, *args, **kwargs):
        """
        Gets an instance of the ``TargetCreateForm`` and populates it with the groups available to the current user.

        :returns: instance of creation form
        :rtype: subclass of TargetCreateForm
        """
        form = super().get_form(*args, **kwargs)
        if self.request.user.is_superuser:
            form.fields['groups'].queryset = Group.objects.all()
        else:
            form.fields['groups'].queryset = self.request.user.groups.all()
        return form


class BiasCalibrationsCadencesList(TemplateView):
    template_name = 'bias_calibrations/bias_calibrations_cadences_list.html'

    
class BiasCalibrationsCadencesView(TemplateView):
    template_name = 'bias_calibrations/bias_calibrations_cadences_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sites'] = Instrument.objects.distinct('site').values_list('site', flat=True)
        return context


class BiasCalibrationsCadencesSiteView(TemplateView):
    template_name = 'bias_calibrations/bias_calibrations_cadences_site_view.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        site = kwargs.get('site')
        instruments_for_site = Instrument.objects.filter(site=site)
        context['site'] = site
        context['instruments'] = instruments_for_site
        return context


# TODO: finish implementation of BiasCalibrationsSubmissionView
class BiasCalibrationsView(FormView):
    template_name = 'bias_calibrations/bias_calibrations_view.html'
    form_class = BiasCalibrationsManualSubmissionForm
    success_url = reverse_lazy('bias_calibrations:bias_calibrations_home')

    def form_invalid(self, form):
        messages.error(self.request, f'The bias calibrations submission form is invalid: {form.errors}.')
        logger.error(f'Invalid form submission for bias calibrations manual submission: {form.errors}.')
        return super().form_invalid(form)

    def form_valid(self, form) -> HttpResponse:
        # This method is called when valid form data has been POSTed.
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial.update({'facility': 'LCO Calibrations'})
        return initial

class BiasCalibrationsForm(FormView):
    template_name = 'bias_calibrations/bias_calibrations_form.html'
    form_class = BiasCalibrationsManualSubmissionForm
    success_url = reverse_lazy('bias_calibrations:bias_calibrations_home')

    def form_invalid(self, form):
        messages.error(self.request, f'The bias calibrations submission form is invalid: {form.errors}.')
        logger.error(f'Invalid form submission for bias calibrations manual submission: {form.errors}.')
        return super().form_invalid(form)

    def form_valid(self, form) -> HttpResponse:
        # This method is called when valid form data has been POSTed.
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial.update({'facility': 'LCO Calibrations'})
        return initial

class BiasCalibrationsTargets(FormView):
    template_name = 'bias_calibrations/bias_calibrations_targets.html'
    form_class = BiasCalibrationsManualSubmissionForm
    success_url = reverse_lazy('bias_calibrations:bias_calibrations_home')

    def form_invalid(self, form):
        messages.error(self.request, f'The bias calibrations submission form is invalid: {form.errors}.')
        logger.error(f'Invalid form submission for bias calibrations manual submission: {form.errors}.')
        return super().form_invalid(form)

    def form_valid(self, form) -> HttpResponse:
        # This method is called when valid form data has been POSTed.
        return super().form_valid(form)

    def get_initial(self):
        initial = super().get_initial()
        initial.update({'facility': 'LCO Calibrations'})
        return initial

class BiasCalibrationsCadenceToggleView(RedirectView):
    pattern_name = 'bias_calibrations:bias_calibrations_cadences'

    def get_redirect_url(self, *args, **kwargs):
        cadence_id = kwargs.pop('pk', None)
        dc = DynamicCadence.objects.get(pk=cadence_id)
        dc.active = not dc.active
        dc.save()
        return super().get_redirect_url(*args, **kwargs)


class BiasCalibrationsCadenceDeleteView(DeleteView):
    model = DynamicCadence
    success_url = reverse_lazy('bias_calibrations:bias_calibrations_cadences')
    template_name = 'bias_calibrations/dynamiccadence_confirm_delete.html'

bias_calibrations/templates/bias_calibrations/partials/bias_calibrations_cadences_list.html
{% load humanize bootstrap4 bias_calibrations_extras %}
<h4>Bias Observation Cadences</h4>
<style type="text/css">
.obs_header{ background-color: #0b3053; color: white }
.cadence_header{ background-color: lightgrey}
</style>
<table class="table table-striped">
    <thead>
        <tr>
            <th colspan="7" class="cadence_header">Cadence Information</th>
            <th colspan="3" class="obs_header">Observation Information</th>
        </tr>
        <tr>
            <!--<th>Site</th>-->
            <th>Code</th>
            <th>Frequency</th>
            <th>Target</th>
            <th>Active</th>
            <th></th>
            <th></th>
            <th>Last modified</th>
            <th>Latest Observation</th>
            <th>Next Observation</th>
            <th>History</th>
        </tr>
    </thead>
    <tbody>
    {% for cadence_data in cadences_data %}
    <tr>
        <!--<td>{{ cadence_data.cadence.cadence_parameters.site }}</td>-->
        <td>{{ cadence_data.cadence.cadence_parameters.instrument_code }}</td>
        <td>{{ cadence_data.cadence.cadence_parameters.cadence_frequency }}</td>
        <td>{{ cadence_data.target.name }}</td>
        <td>{{ cadence_data.cadence.active|yesno:"Active,Inactive" }}</td>
        <td>
        {% if cadence_data.cadence.active %}
            <a href="{% url 'bias_calibrations:cadence_toggle' cadence_data.cadence.id %}" class="btn btn-warning">||</a>
        {% else %}
            <a href="{% url 'bias_calibrations:cadence_toggle' cadence_data.cadence.id %}" class="btn btn-success">></a>
        {% endif %}
        </td>
        <td>
            <a href="{% url 'bias_calibrations:cadence_delete' cadence_data.cadence.id %}" class="btn btn-danger">X</a>
        </td>
        <td>{{ cadence_data.cadence.modified|naturaltime }}</td>

            {% if cadence_data.prev_obs %}
            <td>
                <a href="{% url 'observations:detail' cadence_data.prev_obs.id %}">
                    {{ cadence_data.prev_obs.target }} at {{ cadence_data.prev_obs.scheduled_start }}
                </a>
            </td>
        {% else %}
            <td>None</td>
        {% endif %}
        {% if cadence_data.next_obs %}
            <td>
                {% if cadence_data.next_obs.scheduled_start %}
                <a href="{% url 'observations:detail' cadence_data.next_obs.id %}">
                    {{ cadence_data.next_obs.target }} at {{ cadence_data.next_obs.scheduled_start }}
                </a>
                {% else %}
                <a href="{% url 'observations:detail' cadence_data.next_obs.id %}">
                    {{ cadence_data.next_obs.target }}, not scheduled
                </a>
                {% endif %}
            </td>
        {% else %}
            <td>
                <a href="http://logs.lco.gtn/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(target,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:kubernetes.container_name,negate:!f,type:phrase,value:calibration-tom),query:(match:(kubernetes.container_name:(query:calibration-tom,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:kubernetes.pod_name,negate:!f,type:phrase,value:runcadencestrategies),query:(match:(kubernetes.pod_name:(query:runcadencestrategies,type:phrase))))),index:'logstash-*',interval:auto,query:(match_all:()),sort:!('@timestamp',desc))">
                    Observation not submitted
                </a>
            </td>
        {% endif %}
        <td>
            <a href="https://observe.lco.global/?name={{ cadence_data.cadence.observation_group.name }}&limit=20">
                {{ cadence_data.cadence.observation_group.name }}
            </a>
        </td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="6">
            No targets available.
        </td>
    </tr>
    {% endfor %}
</table>

bias_calibrations/templates/bias_calibrations/partials/bias_calibrations_targets_list.html
{% load calibrations_extras bias_calibrations_extras %}
<h4>Bias Observations</h4>
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Name</th>
        <th scope="col">Type</th>
        <th scope="col">Last Observation</th>
        <th scope="col">Next Observation</th>
        <th scope="col">Seasonal Start</th>
        <th scope="col">Seasonal End</th>
    </tr>
    </thead>
    <tbody>
    {% for target_data in targets_data %}
    <tr>
        <td>
            <a href="{% url 'targets:detail' target_data.target.id %}">{{ target_data.target.name }}</a>
        </td>
        <td>{{ target_data.target.extra_fields.standard_type }}</td>
        {% if not target_data.prev_obs %}
            <td>None</td>
        {% else %}
            <td>
                <a href="{% url 'observations:detail' target_data.prev_obs.id %}">
                    {{ target_data.prev_obs }}
                </a>
            </td>
        {% endif %}
        {% if not target_data.next_obs %}
            <td>None</td>
        {% else %}
            <td>
                <a href="{% url 'observations:detail' target_data.next_obs.id %}">
                    {{ target_data.next_obs }}
                </a>
            </td>
        {% endif %}
        <td>{% display_seasonal_start_or_end target_data.target.extra_fields.seasonal_start %}</td>
        <td>{% display_seasonal_start_or_end target_data.target.extra_fields.seasonal_end %}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="6">
            No bias observation available.
        </td>
    </tr>
    {% endfor %}
</table>

bias_calibrations/templates/bias_calibrations/partials/instrument_filter_site_table.html
{% load static bootstrap4 bias_calibrations_extras %}
<h3><a href="{% url 'bias_calibrations:site_detail' site %}">{{ site }}</a></h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            {% for inst in instruments_at_site %}
            <th>{{ inst.code }}</th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
        {% for filter_name, filter_data in inst_filter_data.items %}
            <tr>
                <td>{{ filter_name }}</td>
                {% for calibration_age in filter_data %}
                    {% if calibration_age is not None and calibration_age != '' %}
                        <td class="{{ calibration_age|css_color }}">{{ calibration_age }} days</td>
                    {% elif calibration_age is None %}
                        <td>{{ calibration_age }}</td>
                    {% else %}
                        <td></td>
                    {% endif %}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
    </tbody>
</table>

bias_calibrations/templates/bias_calibrations/partials/instrument_filters_at_site.html
<div>
    <table class="table table-striped">
        <thead>
            <th>Filter</th>
            <th>Age</th>
        </thead>
        <tbody>
            {% for f in filter_data %}
                <tr>
                    <td>{{ f.filter.name }}</td>
                    <td>
                        {{ f.get_last_calibration_age }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

bias_calibrations/templates/bias_calibrations/partials/instrument_observations_at_site.html
{% load bias_calibrations_extras %}
<div>
    <table class="table">
        <tbody>
            <tbody>
                <th>Date</th>
                <th>Filter</th>
                <th>Status</th>
                {% for obsr in observation_records %}
                <tr>
                    <td>
                        {{ obsr.scheduled_end }}
                    </td>
                    <td>
                        {{ obsr|submitted_filters }}
                    </td>
                    <td>
                        {{ obsr.status }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </tbody>
    </table>
</div>