calibration_tom/urls.py
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('network/', include('network.urls', namespace='network')),
    path('', include('tom_common.urls')),
    path('photometric_standards/', include('photometric_standards.urls', namespace='photometric_standards')),
    path('nres/', include('nres_calibrations.urls', namespace='nres_calibrations')),
    path('calibrations/', include('calibrations.urls')),
    # admin comes from somewhere else
]

# this is to serve static file from a debug Dockerfile environment (performs a findstatic)
# (i.e. without this a local Dockerfile-deployed instance won't find the staticfiles from
# the other INSTALLED_APPS)
urlpatterns += staticfiles_urlpatterns()

network/urls.py
from django.urls import path

from .views import InstrumentListView, InstrumentGroupView, InstrumentDetailView

from .api_views import InstrumentViewSet
from tom_common.api_router import SharedAPIRootRouter

router = SharedAPIRootRouter()
router.register(r'instruments', InstrumentViewSet, 'instruments')

app_name = 'network'

urlpatterns = [
    path('instruments/', InstrumentListView.as_view(), name='instrument_list'),
    path('instrumentgroup/', InstrumentGroupView.as_view(), name='instrumentgroup'),
    path('<int:pk>/', InstrumentDetailView.as_view(), name='detail'),
]

nres_calibrations/urls.py
from django.urls import path

from nres_calibrations.views import NRESCalibrationsView, NRESCalibrationSubmissionView
from nres_calibrations.views import InstrumentListView
from nres_calibrations.views import InstrumentTargetDetailView
from nres_calibrations.views import InstrumentTargetListView
from nres_calibrations.views import InstrumentTypeListView
from nres_calibrations.views import NRESCadenceToggleView, NRESCadenceDeleteView

# app_name is required in order to specify a namespace in include()
app_name = 'nres_calibrations'

urlpatterns = [
    path('nres', NRESCalibrationsView.as_view(), name='nres_home'),
    # TODO: rename this path
    path('submit-cadence', NRESCalibrationSubmissionView.as_view(), name='nres_submission'),
    path('instruments', InstrumentTypeListView.as_view(), name='instrument_type_list'),
    path('instruments/<str:instrument_type>/', InstrumentListView.as_view(), name='instrument_list'),
    path('instruments/<str:instrument_type>/<str:instrument_code>/', InstrumentTargetListView.as_view(),
         name='instrument_target_list'),
    path('instruments/<str:instrument_type>/<str:instrument_code>/<int:pk>/', InstrumentTargetDetailView.as_view(),
         name='instrument_target_detail'),
    path('cadence-toggle/<int:pk>/', NRESCadenceToggleView.as_view(), name='cadence_toggle'),
    path('cadence-delete/<int:pk>/', NRESCadenceDeleteView.as_view(), name='cadence_delete')
]

nres_calibrations/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import ButtonHolder, Column, Layout, Row, Submit
from django import forms
from django.conf import settings
from django.urls import reverse

from tom_targets.models import Target


class NRESCadenceSubmissionForm(forms.Form):
    site = forms.ChoiceField(required=True,
                             choices=[('all', 'All Sites')] + [(site, site) for site in settings.NRES_SITES],
                             label=False)
    cadence_frequency = forms.IntegerField(label=False, min_value=1,
                                   widget=forms.NumberInput(attrs={'placeholder': 'Frequency (hours)'}))
    target_id = forms.ChoiceField(choices=[])  # Display standard type alongside target name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # target_id choices must  be defined here in the __init__ rather than in the class definition
        # because the target_is_in_season method used below is added dynamically to the Target class
        # and it doesn't yet exist at the time of class interpretation, but it does when the instance
        # is made (and __init__ is called)
        self.fields['target_id'] = forms.ChoiceField(  # Create choices for standard_types of targets currently in season
            choices=[(target.id,
                      f"{target.targetextra_set.filter(key='standard_type').first().value} (currently {target.name})")
                     for target in Target.objects.filter(targetextra__key='calibration_type', targetextra__value='NRES')
                     if target.target_is_in_season()],
            label=False
        )
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = reverse('nres_calibrations:nres_submission')

        self.helper.layout = Layout(
            Row(
                Column('site'),
                Column('cadence_frequency'),
                Column('target_id'),
                Column(
                    ButtonHolder(
                        Submit('submit', 'Update or Create Cadence')
                    )
                )
            )
        )

nres_calibrations/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.db import models
from django.db.models.fields.json import KeyTextTransform
from django.db.models.functions import Cast
from django.urls import reverse_lazy
from django.views.generic import DeleteView, DetailView, ListView, RedirectView, TemplateView
from django.views.generic.edit import FormView

from configdb.configdb_connections import ConfigDBInterface
from nres_calibrations.forms import NRESCadenceSubmissionForm
from tom_observations.models import DynamicCadence, ObservationGroup
from tom_targets.models import Target

logger = logging.getLogger(__name__)

configdb = ConfigDBInterface(settings.CONFIGDB_URL)  # TODO: rethink how we store this property


class InstrumentTypeListView(ListView):
    # if not overridden, template_name is <app name>/<model name>_list.html
    #  template_name = ''

    # if not overridden, the context_object_name is <model>_list (used in {% for ... in ... %} template tags
    #  context_object_name = ''
    template_name = 'nres_calibrations/instrument_type_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # add to the context here
        context['kwargs'] = kwargs  # TODO: remove after debugging
        context['template_name'] = self.template_name

        return context

    def get_queryset(self) -> list:
        """
        Extract the a list of instrument_type dictionaries from configdb.
        Dictionary list elements should have 'code' and 'name' keys.

        :return: [{'name': "NAME", 'code': "code"}, ... ]
        """
        queryset = configdb.get_instruments_types('all')

        # process queryset here before returning

        return sorted(queryset, key=lambda item: item['code'])


class InstrumentListView(ListView):
    # if not overridden, template_name is <app name>/<model name >_detail.html
    template_name = 'nres_calibrations/instrument_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # add to the context here
        context['kwargs'] = kwargs  # TODO: remove after debugging
        context['template_name'] = self.template_name  # TODO: remove after debugging

        # insert url parameter(s) into the context
        context['instrument_type'] = self.kwargs.get('instrument_type', '')

        return context

    def get_queryset(self):
        """
        Construct queryset from configdb.
        :return:
        """
        instrument_type = self.kwargs['instrument_type']  # from URL via instance kwargs
        instrument_infos = configdb.get_active_instruments_info(instrument_type=instrument_type)

        queryset = []
        for instrument_info in instrument_infos.values():
            if len(instrument_info) != 1:
                logger.warning(f'configdb instrument_info has more than one list element: {instrument_info}')
            instrument_info = instrument_info[0]  # NOTE: I'm not sure why there is a 1-element list in instrument_info
            queryset.append({
                'code': instrument_info['code'],
                'site': instrument_info['site'],
                'enclosure': instrument_info['observatory'],  # this is really enclosure
                'telescope': instrument_info['telescope'],
                'state': instrument_info['state'],
            })

        return sorted(queryset, key=lambda item: item['code'])


class InstrumentTargetListView(ListView):
    # if not overridden, template_name is <app name>/<model name >_detail.html
    template_name = 'nres_calibrations/instrument_target_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # add to the context here
        context['kwargs'] = kwargs  # TODO: remove after debugging
        context['template_name'] = self.template_name  # TODO: remove after debugging

        # insert url parameter(s) into the context
        context['instrument_type'] = self.kwargs.get('instrument_type', '')
        context['instrument_code'] = self.kwargs.get('instrument_code', '')

        return context

    def _get_target_list_for_instrument(self):  # noqa
        """
        Return the Targets for the given instrument.
        (instrument_type and instrument_code available in instance self.kwargs).
        :return:
        """
        return Target.objects.all()  # noqa

    # TODO: specify model = Target ; this override is unnecessary
    def get_queryset(self):
        targets = self._get_target_list_for_instrument()

        # here, convert the target list in to a sane queryset
        queryset = targets  # the degenerate case

        return queryset


class InstrumentTargetDetailView(DetailView):
    # if not overridden, template_name is <app name>/<model name >_detail.html
    template_name = 'nres_calibrations/instrument_target_detail.html'
    model = Target

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # add to the context here

        # target = kwargs['object']
        # extras = {key['name']: target.extra_fields.get(key['name'], '') for key in EXTRA_FIELDS if
        #           not key.get('hidden')}
        # context['extras'] = extras
        # context['target'] = target

        # insert url parameter(s) into the context
        context['instrument_type'] = self.kwargs.get('instrument_type', '')
        context['instrument_code'] = self.kwargs.get('instrument_code', '')
        context['target_id'] = self.kwargs.get('target_id', 1)

        context['kwargs'] = kwargs  # TODO: remove after debugging
        context['template_name'] = self.template_name  # TODO: remove after debugging

        return context


class NRESCalibrationsView(TemplateView):
    template_name = 'nres_calibrations/nres_calibrations_view.html'


class NRESCalibrationSubmissionView(FormView):
    form_class = NRESCadenceSubmissionForm
    success_url = reverse_lazy('nres_calibrations:nres_home')
    # TODO: make sure this template_name assignment makes sense
    #  (it's required for tests.TestNRESCalibrationSubmissionView)
    template_name = 'nres_calibrations/nres_calibrations_view.html'

    def form_invalid(self, form):
        messages.error(self.request, f'The form is invalid: {form.errors}.')
        logger.error(f'Invalid form submission for NRES cadence submission: {form.errors}.')
        return super().form_invalid(form)

    def _get_active_requested_nres_sites(self, requested_sites):
        """
        :return: list of site-code strings which are both active (SCHEDULABLE or COMMISSIONING) and requested by the form.
        """
        active_sites = []  # the sites with active (SCHEDULABLE or COMMISSIONING) NRES instruments
        for telcode, instruments in configdb.get_active_instruments_info(
                instrument_type=settings.NRES_INSTRUMENT_TYPE,
                include_commissioning=True).items():
            active_sites.append(instruments[0]['site'])

        active_requested_sites = [site for site in requested_sites if site in active_sites]
        return active_requested_sites

    def form_valid(self, form):
        """For each (configdb-approved) site, find the DynamicCadences that have the same
        target standard_type as the new (form-given) target and update them.
        """
        requested_site = form.cleaned_data['site']
        cadence_frequency = form.cleaned_data['cadence_frequency']
        target_id = form.cleaned_data['target_id']
        target = Target.objects.get(pk=target_id)

        # Sort out which sites are both requested and have scheduable/commissioning nres instruments
        requested_sites = settings.NRES_SITES  # handles the 'all' case
        if requested_site != 'all':
            requested_sites = [requested_site]
        active_requested_nres_sites = self._get_active_requested_nres_sites(requested_sites)

        # Get standard type of this dynamic cadence
        standard_type = target.targetextra_set.filter(key='standard_type').first().value
        # we have the target_id so we shouldn't need this
        targets_for_standard_type = Target.objects.filter(targetextra__key='standard_type',
                                                          targetextra__value=standard_type)
        # TODO: the standard_type should become one of the (arbitrary JSON) cadence_parameters
        # TODO: because (why?)

        # annotate the all the cadences with the target.id of their targets...
        dynamic_cadences = DynamicCadence.objects.annotate(
            target_id=Cast(KeyTextTransform('target_id', 'cadence_parameters'), models.IntegerField()))
        # ... so we can filter them (the dynamic cadences) down to the ones that match the standard_type
        dynamic_cadences = dynamic_cadences.filter(target_id__in=targets_for_standard_type)

        for site in active_requested_nres_sites:
            dynamic_cadences_for_site = dynamic_cadences.filter(cadence_parameters__site=site)
            if dynamic_cadences_for_site.count() == 0:
                # we need to create the DynamicCadence here (for the site we're looping through)
                og = ObservationGroup.objects.create(name=f'NRES {standard_type} calibration for {site.upper()}')
                DynamicCadence.objects.create(
                    cadence_strategy='NRESCadenceStrategy',
                    cadence_parameters={
                        'target_id': target_id,
                        'cadence_frequency': cadence_frequency,
                        'site': site
                    },
                    observation_group=og,
                    active=True
                )
            # here we don't create, but only  update the existing DynamicCadence (for the site)
            for dc in dynamic_cadences_for_site:
                dc.cadence_parameters['target_id'] = target.id

nres_calibrations/templates/nres_calibrations/index.html
{% extends 'tom_common/index.html' %}
<!-- nres_calibrations/index.html -->
{% block content %}
<!-- block content -->
  {% block breadcrumbs %}
  <a href="{% url 'nres_calibrations:instrument_type_list' %}">NRES Calibrations Home</a>
  <!-- endblock breadcrumbs -->
  {% endblock breadcrumbs %}

<h1>NRES Calibrations Index Page</h1>
{% comment %}
TODO: this should loop through a context or queryset supplied list of instrument types
and link to a ListView of Instruments for that InstrumentType
TODO: this is
<a href="{% url 'nres_calibrations:instrument_type_list' %}">Instrument Type List (instrument_type to be listed)</a>
<p/>
<a href="{% url 'nres_calibrations:instrument_type_list' %}">Instrument List (instrument_type to be listed)</a>
{% endcomment %}

<!-- endblock content -->
{% endblock content %}

nres_calibrations/templates/nres_calibrations/instrument_list.html
{% extends 'nres_calibrations/index.html' %}
<!-- nres_calibrations/instrument_list.html -->
{% block content %}
<!-- block content -->
{% block breadcrumbs %}
    {{ block.super }} &raquo;
    <a href="{% url 'nres_calibrations:instrument_list' instrument_type %}">{{ instrument_type }} Instrument List</a>
{% endblock breadcrumbs%}

<h1>{{ instrument_type }} Instrument List</h1>
    <div>
        <table class='table table-striped'>
            <thead>
            <tr>
                <th scope="col">Instrument Code</th>
                <th scope="col">Instrument State</th>
                <th scope="col">Site</th>
                <th scope="col">Enclosure</th>
                <th scope="col">Telescope</th>
            </tr>
            </thead>
            <tbody>
            {% for instrument in object_list %}
            <tr>
                <td>
                    <a href="{% url 'nres_calibrations:instrument_target_list' instrument_type instrument.code %}">{{instrument.code}}</a>
                </td>
                <td>{{instrument.state}}</td>
                <td>{{instrument.site}}</td>
                <td>{{instrument.enclosure}}</td>
                <td>{{instrument.telescope}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<hr/>

{% comment %}
<h3>debug info:</h3>
<p>get_context_data kwargs: {{ kwargs }}</p>
<p>object_list: {{ object_list }}</p>
<p>instrument_type: {{ instrument_type }}</p>
<p>instrument_code: {{ instrument_code }}</p>
{% endcomment %}

<!-- endblock content -->
{% endblock content %}

nres_calibrations/templates/nres_calibrations/instrument_target_detail.html
{% extends 'nres_calibrations/instrument_target_list.html' %}
<!-- nres_calibrations/instrument_target_detail.html -->
{% load tom_common_extras targets_extras observation_extras calibrations_extras nres_calibrations_extras %}
{% block content %}
<!-- block content -->
<p>
    {% block breadcrumbs %}
        {{ block.super }} &raquo;
        <a href="{% url 'nres_calibrations:instrument_target_detail' instrument_type instrument_code target_id %}">{{ target.name }} Target Detail</a>
    {% endblock breadcrumbs%}
</p>

<div style="display: inline;">
    <h3>{{ target.name }}</h3><h5>{% standard_type target %}{% sitecode_tag instrument_code %}</h5>
</div>
<div class="row">
    <div class="col-md-6">Last observed: {% last_observation_date target %}</div>
    <div class="col-md-6">RV scatter = {% rv_average target %}</div>
</div>
<div class="row">
    <div class="col-md-6">Next scheduled: {% next_observation_date target %}</div>
    <div class="col-md-6">Number of observations: {% observation_count target 'COMPLETED' %}</div>
</div>
<hr/>

{% rv_plot target %}

<div class="row">
    <div class="col-md-8">
        <div class="row">
            {% observation_plan target 'LCO' length=3 airmass_limit=2 %}
        </div>
        <div class="row">
            {% target_observation_list target %}
        </div>
    </div>

    <div class="col-md-4">
        <div class="col-md-12">
            <h6>Target Info:</h6>
            <div class="row">RA = {{ target.ra | deg_to_sexigesimal:"hms" }}</div>
            <div class="row">Dec = {{ target.ra | deg_to_sexigesimal:"hms" }}</div>
            <div class="row">V = {{ target.tags.v_mag }}</div>
        </div>
    </div>
</div>

{% comment %}
<hr/>
<h3>debug data:</h3>
<p>get_context_data kwargs: {{ kwargs }}</p>
<p>get_context_data context: {{ context }}</p>
<p>get_context_data template_name: {{ template_name }}</p>
<p>get_context_data instrument_type: {{ instrument_type }}</p>
<p>get_context_data instrument_code: {{ instrument_code }}</p>
{% endcomment %}

<!-- endblock content -->
{% endblock content %}

nres_calibrations/templates/nres_calibrations/instrument_target_list.html
{% extends 'nres_calibrations/instrument_list.html' %}
<!-- nres_calibrations/instrument_target_list.html -->
{% load calibrations_extras %}
{% block content %}
<!-- block content -->
{% block breadcrumbs %}
    {{ block.super }} &raquo;
    <a href="{% url 'nres_calibrations:instrument_target_list' instrument_type instrument_code %}">{{ instrument_code }} Instrument Target List</a>
{% endblock breadcrumbs%}

<h1>{{ instrument_code }} Target List</h1>
    <div>
        <table class='table table-striped'>
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Active</th>
                <th scope="col">Last Observation</th>
                <th scope="col">Next Observation</th>
                <th scope="col">Seasonal Start</th>
                <th scope="col">Seasonal End</th>
            </tr>
            </thead>
            <tbody>
            {% for target in object_list %}
            <tr>
                <td>
                    <a href="{% url 'nres_calibrations:instrument_target_detail' instrument_type instrument_code target.id %}">{{target.name}}</a>
                </td>
                <td>{{ target.extra_fields.standard_type }}</td>
                <td>{{target.extra_fields.nres_active_target}}</td>
                <td>N/A</td>
                <td>N/A</td>
                <td>{% display_seasonal_start_or_end target.extra_fields.seasonal_start %}</td>
                <td>{% display_seasonal_start_or_end target.extra_fields.seasonal_end %}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<hr/>

<!-- endblock content -->
{% endblock content %}

nres_calibrations/templates/nres_calibrations/instrument_type_list.html
{% extends 'nres_calibrations/index.html' %}
<!-- nres_calibrations/instrument_type_list.html -->
{% block content %}
<!-- block content -->
{% block breadcrumbs %}
    {{ block.super }} &raquo;
    <a href="{% url 'nres_calibrations:instrument_type_list' %}">Instrument Types</a>
{% endblock breadcrumbs%}

<h1>Instrument Types</h1>
    <div>
        <table class='table table-striped'>
            <thead>
            <tr>
                <th scope="col">Instrument Type Code</th>
                <th scope="col">Instrument Type Name</th>
            </tr>
            </thead>
            <tbody>
            {% for instrument_type in object_list %}
            <tr>
                <td>
                    <a href="{% url 'nres_calibrations:instrument_list' instrument_type.code %}">{{instrument_type.code}}</a>
                </td>
                <td>
                {{instrument_type.name}}
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<hr/>


{% comment %}
<h3>debug info:</h3>
<p>get_context_data kwargs: {{ kwargs }}</p>
<p>object_list: {{ object_list }}</p>
<p>instrument_types: {{ instrument_types }}</p>
{% endcomment %}

<!-- endblock content -->
{% endblock content %}

nres_calibrations/templates/nres_calibrations/nres_calibrations_view.html
{% extends 'nres_calibrations/index.html' %}
{% load nres_calibrations_extras %}
{% block content %}
{% nres_cadence_list %}
<hr/>
{% nres_submission_form %}
<hr/>
{% nres_targets_list %}
<p></p>
    <a class="btn btn-primary" href="{% url 'nres_calibrations:instrument_type_list' %}">View ConfigDB Instruments -></a>
</p>
{% endblock content %}